# Generated by Django 3.1 on 2020-08-29 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tutorial_content',
            new_name='post_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tutorial_published',
            new_name='post_published',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tutorial_title',
            new_name='post_title',
        ),
    ]
