# Generated by Django 3.1 on 2020-08-29 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200828_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_published',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
