# Generated by Django 3.1 on 2020-08-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200828_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
