# Generated by Django 3.1 on 2020-09-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200901_0237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
