# Generated by Django 3.1 on 2020-09-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200908_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_upvotes',
            field=models.IntegerField(default='0'),
        ),
    ]
