# Generated by Django 3.1 on 2020-09-10 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0024_post_total_upvotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvoted_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvoted_post', to='main.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvoted_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
