# Generated by Django 3.1 on 2020-09-10 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_upvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
