# Generated by Django 3.1 on 2020-09-10 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0027_upvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upvote',
            old_name='upvoted_post',
            new_name='post',
        ),
        migrations.AddField(
            model_name='upvote',
            name='value',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together={('user', 'post', 'value')},
        ),
    ]
