# Generated by Django 3.1 on 2020-09-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20200909_2358'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='value',
        ),
    ]
