# Generated by Django 3.1 on 2020-09-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ticker',
            field=models.TextField(null=True),
        ),
    ]
