# Generated by Django 3.1 on 2020-09-14 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20200913_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_traded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
