# Generated by Django 3.1 on 2020-09-16 03:14

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('main', '0039_auto_20200913_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_traded',
            field=models.DateTimeField(verbose_name='Date Traded'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Press Enter or comma to seperate tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
