# Generated by Django 3.1 on 2020-09-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20200919_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_message',
            field=models.TextField(null=True),
        ),
    ]
